# Generated by Django 5.0.4 on 2024-04-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='noofguests',
            field=models.SmallIntegerField(default=1),
        ),
    ]
